import { ModelPreset } from './types';

// dModel / numLayers / numHeads are kept small on purpose — this is a
// visualization built for intuition, not a production model config.
export const MODELS: ModelPreset[] = [
  {
    id: 'gpt',
    name: 'GPT-5',
    org: 'OpenAI',
    accent: '#10a37f',
    accentSoft: '#10a37f2a',
    dModel: 16,
    numLayers: 4,
    numHeads: 4,
    vocabLabel: '~200K token vocab',
    contextLabel: '128K context window',
    description: 'A dense transformer decoder trained on next-token prediction at massive scale.',
  },
  {
    id: 'claude',
    name: 'Claude Opus',
    org: 'Anthropic',
    accent: '#d97757',
    accentSoft: '#d977572a',
    dModel: 16,
    numLayers: 4,
    numHeads: 4,
    vocabLabel: '~100K token vocab',
    contextLabel: '200K context window',
    description: 'A dense transformer refined with Constitutional AI for helpful, honest behavior.',
  },
  {
    id: 'grok',
    name: 'Grok',
    org: 'xAI',
    accent: '#18181b',
    accentSoft: '#18181b1f',
    dModel: 16,
    numLayers: 4,
    numHeads: 4,
    vocabLabel: '~130K token vocab',
    contextLabel: '128K context window',
    description: 'A mixture-of-experts transformer that routes each token to specialist sub-networks.',
    moe: { numExperts: 8, topK: 2 },
  },
  {
    id: 'gemini',
    name: 'Gemini',
    org: 'Google DeepMind',
    accent: '#4285f4',
    accentSoft: '#4285f42a',
    dModel: 16,
    numLayers: 4,
    numHeads: 4,
    vocabLabel: '~250K token vocab',
    contextLabel: '1M+ context window',
    description: 'A natively multimodal dense transformer built for very long-context attention.',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    org: 'DeepSeek AI',
    accent: '#5b7cfa',
    accentSoft: '#5b7cfa2a',
    dModel: 16,
    numLayers: 4,
    numHeads: 4,
    vocabLabel: '~100K token vocab',
    contextLabel: '128K context window',
    description: 'A sparse mixture-of-experts transformer optimized for efficient compute.',
    moe: { numExperts: 8, topK: 2 },
  },
];

export const DEFAULT_MODEL = MODELS[1];
